package model

var Entities = []interface{}{
	&Account{},
	&Admin{},
	&Attendance{},
	&Subject{},
	&RelationClassroomSubject{},
	&Schedule{},
	&School{},
	&Teacher{},
	&TeacherData{},
	&AcademicYear{},
	&Classroom{},
	&Student{},
	&StudentData{},
	&StudentFamilyData{},
	&AddressData{},
	&SubjectComponent{},
	&Score{},
	&MassCreate{},
	&RewardPunishment{},
	&Feedback{},
	&FeedbackScore{},
	&FeedbackQuestion{},
	&CustomerDetails{},
	&PaymentLink{},
	&Purchase{},
	&DynamicAmount{},
	&Transaction{},
	&Bill{},
	&MidtransCredentials{},
	&Event{},
	&EventDraft{},
	&LogData{},
}
