worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://0.0.0.0:8080;
      }
    }

    server {
        listen 81;
        server_name localhost;

        location / {
            proxy_pass http://0.0.0.0:8083;
      }
    }

    server {
        listen 83;
        server_name localhost;

        location / {
            proxy_pass http://0.0.0.0:1337;
      }
    }
}